# config file for the job execution on cluster 

__default__:
    account: "ClinicalMicrobio"
    cpus-per-task: 1
    time: "01:00:00"    
    mem: 8000
    output: "logs/{rule}-%j.out"
    #output: "logs/{rule}.out"
    error: "logs/{rule}-%j.err"
    #error: "logs/{rule}.err"

#main:
#    time: "02:00:00"
#    mem: 16384

depth_fig:
  time: "24:00:00"
  mem: 16000